version: "3.8"
name: chat-bridge-logs

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build: ../api
    env_file: ../infra/.env
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"

  worker:
    build: ../worker
    env_file: ../infra/.env
    depends_on:
      - db
      - redis

  ui:
    build: ../ui
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"
