
# infra/docker-compose.yml
name: chat-bridge-logs

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    # Do NOT publish 6379 unless you truly need it.
    expose:
      - "6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build: ../api
    env_file: ./.env
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"

  worker:
    build: ../worker
    env_file: ./.env
    depends_on:
      - db
      - redis

  ui:
    build: ../ui
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"

volumes:
  db_data:
  minio_data:
